### ISSUE TITLE
Installation breaking with error ./swpb file not found, while using pacman.

### ISSUE THREAD

**Issue by whoisdinanath** [pwnwriter/ewm#8]

**Comment by pwnwriter** [comment]
`AUR` installation is broken rn, 

You can use makefile.
- Clone the repo
- `sudo make install`

And yeah, I removed `swpb` (to make the wm clean), a posix script for taking screenshots and other to [`rice`](https://github.com/pwnwriter/ewm/tree/rice) branch.
